# $FreeBSD$

PORTNAME=	electron
DISTVERSION=	v5.0.0
DISTVERSIONSUFFIX=	-beta.4
CATEGORIES=	devel
USE_GITHUB=	yes


DIST_SUBDIR=	${PORTNAME}

MAINTAINER=	youremail@example.com
COMMENT=	Cat chasing a mouse all over the screen

.include <bsd.port.mk>
